### ISSUE TITLE
Classes not being sampled equally

### ISSUE THREAD

**Issue by anantzoid** [issamemari/pytorch-multilabel-balanced-sampler#1]
Thanks for putting this out there!

I tried running this and didn't get the results I was hoping for. It looks like a [class is chosen randomly](https://github.com/issamemari/pytorch-multilabel-balanced-sampler/blob/master/sampler.py#L48) each time `__next__` is called, thus not really ensuring every class is chosen at least `batch_size / n_classes` times. And this is what I observed.

Could you please clarify?

Thanks,
Anant

**Comment by issamemariold** [comment]
Hi @anantzoid! Thank you for your interest.

Indeed, the class is chosen uniformly at random each time. This indeed does not guarantee that every class will be chosen at least `batch_size / n_classes`.

The intended behavior is that as the batch size goes to infinity, the number of samples of each class goes to `batch_size / n_classes`.

**Comment by issamemariold** [comment]
@anantzoid I just added an option [here](https://github.com/issamemari/pytorch-multilabel-balanced-sampler/commit/431391809d02bc1d3a5e7d7f86cf79db8dbe20c3) to cycle through the classes sequentially instead of choosing the class randomly each time. This should guarantee that the number of samples of each class is `batch_size / n_classes`.

Let me know if that works for you!

**Comment by anantzoid** [comment]
That was helpful. Thanks!
